include: package:very_good_analysis/analysis_options.yaml

# Uncomment the following section to specify additional rules.

linter:
   rules:
     public_member_api_docs: true
     avoid_setters_without_getters: false
     sort_constructors_first: false
     lines_longer_than_80_chars: false