name: adaptive_card_builder
description: A Dart package providing model classes and builders to create adaptive card JSON definitions
version: 0.2.0
repository: https://github.com/NicolaVerbeeck/adaptive_card_builder_dart

environment:
  sdk: ^3.3.0

dependencies:
  meta: ">=1.0.0 <2.0.0"

dev_dependencies:
  lints: ">=4.0.0 <6.0.0"
  test: ^1.24.0
  very_good_analysis: ^6.0.0
